#!/usr/bin/env ruby

# use this option if you want to wipe the db
# "-m 'rake build:db'"
#
#

require 'readline'

def confirm_continue
  print "Do you want to continue? (Yes/n): "
  r = Readline.readline()
  if r != "Yes"
    puts "Not deploying. Bye."
    exit
  end
end

puts "WARNING: you are about to deploy to PHOTOS STAGING."
#confirm_continue
puts
print "Enter the tag or branch we should be based on for the deploy (optional): "
tag = Readline.readline()
tag = "master" if tag.empty?

puts
print "Do you want to skip migration (zero-downtime)? (Yes/n): "
skip_migrate = Readline.readline()
if (skip_migrate == "Yes")
  migrate = "--no-migrate"
else
  migrate = ""
end

options = ARGV[0] ? ARGV[0] : ""

cmd = "ey deploy -e photos_staging --ref #{tag} #{migrate} -v " + options
puts
puts "About to deploy to PHOTOS STAGING with the following command: "
puts "\n" + cmd + "\n\n"

confirm_continue

# ok, finally run the command
# this is purposefully difficult to avoid accidental deploys
# to production
Kernel.exec(cmd)
