#!/usr/bin/env ruby

# use this option if you want to wipe the db
# "-m 'rake build:db'"
#
#

require 'readline'

def confirm_continue
  print "Do you want to continue? (Yes/n): "
  r = Readline.readline()
  if r != "Yes"
    puts "Not deploying. Bye."
    exit
  end
end

puts "WARNING: you are about to deploy to PHOTOS STAGING."
#confirm_continue
puts
print "Enter the tag or branch we should be based on for the deploy (optional): "
tag = Readline.readline()
tag = "master" if tag.empty?

puts
print "Do you want zero downtime? (Yes/n): "
zero_downtime = Readline.readline()
if (zero_downtime == "Yes")
  downtime = ""
else
  downtime = "--downtime"
end

options = ARGV[0] ? ARGV[0] : ""

cmd = "zz deploy #{downtime} --migrate -g photos_staging --tag #{tag} #{options}"
puts
puts "About to deploy to PHOTOS STAGING with the following command: "
puts "\n" + cmd + "\n\n"

confirm_continue

# ok, finally run the command
# this is purposefully difficult to avoid accidental deploys
# to production
Kernel.exec(cmd)
