#
#   Copyright 2010, ZangZing LLC;  All rights reserved.  http://www.zangzing.com
#
#  WARNING: INDENTATION HAS SEMANTIC MEANING! BE CAREFUL WHEN EDITING
#
#  agent_config.yml
#

agents:
  '0.5': &agent_version_default
    darwin:
      '6.5':
        check: OK
      default:
        check: update
        update_type: optional
        check_interval: 1800
        url: https://s3.amazonaws.com/zzagent/ZangZing-Setup-v0.001-260.pkg
        version: v0.001-260
        message: This is the one you really cant miss
    win32:
      '5.3':
        check: update
        update_type: required
        url: http://www.keep-the-drama-for-your-mama.com/the53source.exe
        url_readme: http://www.keep-the-drama-for-your-mama.com/the53readme.txt
        message: This is the one you really cant miss
      '6.1':
        check: update
        update_type: optional
        url: http://www.keep-the-drama-for-your-mama.com/the61source.exe
        url_readme: http://www.keep-the-drama-for-your-mama.com/the61readme.txt
        message: This is the one you really cant miss
      default:
          check: update
          update_type: optional
          check_interval: 1800
          url: https://s3.amazonaws.com/zzagent/ZangZing-Setup-v0.001-260.exe
          version: v0.001-260
          message: This is the one you really cant miss
    default:
      default:
        check: OK
        check_interval: 1800
  default:
    <<: *agent_version_default