package_assets: on
compress_assets: off
embed_assets: off


javascripts:
  jquery_lib:
    - public/javascripts/jquery-lib/jquery.ui.core.js
    - public/javascripts/jquery-lib/jquery.ui.widget.js
    - public/javascripts/jquery-lib/jquery.ui.mouse.js
    - public/javascripts/jquery-lib/jquery.ui.position.js
    - public/javascripts/jquery-lib/jquery.effects.core.js
    - public/javascripts/jquery-lib/*.js
  zz:
    - public/javascripts/zz/*.js
  zz_oauthmanager:
    - public/javascripts/zz-oauthmanager/oauthmanager.js
  swf:
    - public/javascripts/swf/*.js

stylesheets:
  common:
    - public/stylesheets/*.css
