package_assets: always
compress_assets: always
embed_assets: off


javascript_compressor: closure
compressor_options:
  compilation_level: "ADVANCED_OPTIMIZATIONS"
#  compilation_level: "SIMPLE_OPTIMIZATIONS"
#  code_url:
  #js_externs:
  #  - public/externs/externs.js
   
  externs: public/javascripts/externs/externs.js
#	- http\://zza.zangzing.com/zza.js




javascripts:
  all:
#    - public/javascripts/jquery-lib/jquery.ui.core.js
#    - public/javascripts/jquery-lib/jquery.ui.widget.js
#    - public/javascripts/jquery-lib/jquery.ui.mouse.js
#    - public/javascripts/jquery-lib/jquery.ui.position.js
#    - public/javascripts/jquery-lib/jquery.effects.core.js
    - public/javascripts/jquery-lib/*.js
    - public/javascripts/lib/*.js
    - public/javascripts/zz/*.js
    - public/javascripts/zz-oauthmanager/oauthmanager.js
    - public/javascripts/movie/*.js

stylesheets:
  common:
    - public/stylesheets/reset.css
    - public/stylesheets/main.css
    - public/stylesheets/*.css
