package_assets: on
compress_assets: on
embed_assets: off

javascript_compressor: closure
compressor_options:
  compilation_level: "SIMPLE_OPTIMIZATIONS"



javascripts:
  jquery:
    - public/javascripts/jquery/*.js

  lib:
    - public/javascripts/jquery-lib/jquery.ui.core.js
    - public/javascripts/jquery-lib/jquery.ui.widget.js
    - public/javascripts/jquery-lib/jquery.ui.mouse.js
    - public/javascripts/jquery-lib/jquery.ui.position.js
    - public/javascripts/jquery-lib/jquery.effects.core.js
    - public/javascripts/jquery-lib/*.js
    - public/javascripts/lib/swfupload.js
    - public/javascripts/lib/*.js
  zz:
    - public/javascripts/zz/license.js
    - public/javascripts/zz/namespaces.js
    - public/javascripts/zz/zza.js
    - public/javascripts/zz/routes.js
    - public/javascripts/zz/*.js
  zz_oauthmanager:
    - public/javascripts/zz-oauthmanager/oauthmanager.js
  movie:
    - public/javascripts/movie/*.js
  store:
    - public/javascripts/zz/routes.js
    - public/javascripts/store/rails.js
    - public/javascripts/store/application.js
    - public/javascripts/store/less-1.1.3.js
    - public/javascripts/store/jquery.infieldlabel.js
    - public/javascripts/jquery-lib/jquery.validate.js
    - public/javascripts/jquery-lib/jquery.ui.core.js
    - public/javascripts/jquery-lib/jquery.ui.widget.js
    - public/javascripts/jquery-lib/jquery.ui.button.js
    - public/javascripts/jquery-lib/jquery.ui.numeric.js
    - public/javascripts/lib/spin.js
    - public/javascripts/lib/cssua.js
    - public/javascripts/store/checkout.js
  store_admin:
    - public/javascripts/store/admin/rails.js
    - public/javascripts/store/admin/jquery.ui.js
    - public/javascripts/store/admin/jquery.suggest.js
    - public/javascripts/store/admin/jquery.tokeninput.js
    - public/javascripts/store/admin/jquery.delayedobserver.js
    - public/javascripts/store/admin/admin.js
    - public/javascripts/store/admin/nested-attribute.js
    - public/javascripts/store/admin/zone.js
    - public/javascripts/store/admin/calculator.js
    - public/javascripts/store/admin/gateway.js
    - public/javascripts/store/admin/jquery.alerts/jquery.alerts.js
    - public/javascripts/store/admin/jquery.autocomplete.js
    - public/javascripts/store/admin/datepicker.js
    - public/javascripts/store/admin/unobtrusive_handlers.js
  store_admin_template:
    - public/javascripts/store/admin/jquery.template.js

stylesheets:
  common:
    - public/stylesheets/reset.css
    - public/stylesheets/main.css
    - public/stylesheets/*.css
  store:
    - public/stylesheets/buttons.css
    - public/stylesheets/jquery-lib/jquery.ui.button.css
    - public/stylesheets/jquery-lib/jquery.ui.theme.css
    - public/stylesheets/jquery-lib/jquery-ui-numeric.css
    - public/stylesheets/store/checkout.css
    - public/stylesheets/store/bootstrap.css
  store_admin:
    - public/stylesheets/store/admin/*.css
    - public/javascripts/store/admin/jquery.alerts/jquery.alerts.css
    - public/javascripts/store/admin/jquery.alerts/jquery.alerts.spree.css
    - public/stylesheets/store/admin/datepicker.css
