package_assets: on
compress_assets: on
embed_assets: off

javascript_compressor: closure
compressor_options:
  compilation_level: "SIMPLE_OPTIMIZATIONS"



javascripts:
  jquery:
    - public/javascripts/jquery/*.js
  lib:
    - public/javascripts/jquery-lib/jquery.ui.core.js
    - public/javascripts/jquery-lib/jquery.ui.widget.js
    - public/javascripts/jquery-lib/jquery.ui.mouse.js
    - public/javascripts/jquery-lib/jquery.ui.position.js
    - public/javascripts/jquery-lib/jquery.effects.core.js
    - public/javascripts/jquery-lib/*.js
    - public/javascripts/lib/swfupload.js
    - public/javascripts/lib/*.js
  zz:
    - public/javascripts/zz/license.js
    - public/javascripts/zz/zza.js
    - public/javascripts/zz/routes.js
    - public/javascripts/zz/*.js
  css:
    - public/javascripts/css/*.js
  zz_oauthmanager:
    - public/javascripts/zz-oauthmanager/oauthmanager.js
  movie:
    - public/javascripts/movie/*.js
  store:
    - public/javascripts/store/jquery.infieldlabel.js
    - public/javascripts/zz/routes.js
    - public/javascripts/store/application.js
    - public/javascripts/jquery-lib/jquery.validate.js
    - public/javascripts/lib/spin.js
    - public/javascripts/store/checkout.js
    - public/javascripts/lib/iphone-style-checkboxes.js
    - public/javascripts/store/bootstrap-modal.js
    - public/javascripts/store/bootstrap-twipsy.js
    - public/javascripts/store/bootstrap-popover.js
    - public/javascripts/lib/zendesk.js
    - public/javascripts/zz/zzat.js

  less:
    - public/javascripts/store/less-1.1.3.js

  store_admin:
    - public/javascripts/store/admin/jquery-1.4.2.js
    - public/javascripts/store/admin/rails.js
    - public/javascripts/store/admin/jquery-ui.js
    - public/javascripts/store/admin/jquery.alerts/jquery.alerts.js
    - public/javascripts/store/admin/jquery.suggest.js
    - public/javascripts/store/admin/jquery.tokeninput.js
    - public/javascripts/store/admin/jquery.delayedobserver.js
    - public/javascripts/store/admin/admin.js
    - public/javascripts/store/admin/nested-attribute.js
    - public/javascripts/store/admin/zone.js
    - public/javascripts/store/admin/calculator.js
    - public/javascripts/store/admin/gateway.js
    - public/javascripts/store/admin/lang/*.js
    - public/javascripts/store/localization/*.js
    - public/javascripts/store/admin/datepicker.js
    - public/javascripts/store/admin/jquery.autocomplete.js
  store_admin_taxonomies:
    - public/javascripts/store/admin/taxonomy.js
    - public/javascripts/store/admin/jquery.cookie.js
    - public/javascripts/store/admin/jsTree/jquery.jstree.js
  store_admin_template:
    - public/javascripts/store/admin/jquery.template.js
  store_admin_handlers:
    - public/javascripts/store/admin/unobtrusive_handlers.js
  store_admin_dashboard:
    - public/javascripts/store/admin/jqPlot/jquery.jqplot.js
    - public/javascripts/store/admin/jqPlot/plugins/*.js
    - public/javascripts/store/admin/dashboard.js
  store_admin_excanvas:
    - public/javascripts/store/admin/jqPlot/excanvas.js

  shared:
    - public/javascripts/shared/*.js

stylesheets:
  common:
    - public/stylesheets/main.css
    - public/stylesheets/*.css
  store:
    - public/stylesheets/buttons.css
    - public/stylesheets/dialog.css
    - public/stylesheets/store/checkout.css
    - public/stylesheets/store/bootstrap.css
    - public/stylesheets/iphone-style-checkboxes.css
    - public/stylesheets/photo.css
    - public/stylesheets/picon.css
    - public/stylesheets/zendesk.css
  store_admin:
    - public/stylesheets/store/admin/admin-reset.css
    - public/stylesheets/store/admin/grids.css
    - public/stylesheets/store/admin/admin-typography.css
    - public/stylesheets/store/admin/admin-forms.css
    - public/stylesheets/store/admin/admin-tables.css
    - public/stylesheets/store/admin/admin.css
    - public/stylesheets/store/admin/autocomplete.css
    - public/stylesheets/store/admin/token-input.css
    - public/javascripts/store/admin/jquery.alerts/jquery.alerts.css
    - public/javascripts/store/admin/jquery.alerts/jquery.alerts.spree.css
    - public/stylesheets/store/admin/datepicker.css
    - public/javascripts/store/admin/jsTree/themes/apple/style.css
    - public/stylesheets/store/admin/dashboard.css
