package_assets: on
compress_assets: on
embed_assets: off

javascript_compressor: closure
compressor_options:
  compilation_level: "SIMPLE_OPTIMIZATIONS"



javascripts:
  jquery:
    - public/javascripts/jquery/*.js
  lib:
    - public/javascripts/jquery-lib/jquery.ui.core.js
    - public/javascripts/jquery-lib/jquery.ui.widget.js
    - public/javascripts/jquery-lib/jquery.ui.mouse.js
    - public/javascripts/jquery-lib/jquery.ui.position.js
    - public/javascripts/jquery-lib/jquery.effects.core.js
    - public/javascripts/jquery-lib/*.js
    - public/javascripts/lib/swfupload.js
    - public/javascripts/lib/*.js
  zz:
    - public/javascripts/zz/license.js
    - public/javascripts/zz/namespaces.js
    - public/javascripts/zz/zza.js
    - public/javascripts/zz/routes.js
    - public/javascripts/zz/*.js
  zz_oauthmanager:
    - public/javascripts/zz-oauthmanager/oauthmanager.js
  movie:
    - public/javascripts/movie/*.js
#  store:
#    - public/store/javascripts/*.js

stylesheets:
  common:
    - public/stylesheets/reset.css
    - public/stylesheets/main.css
    - public/stylesheets/*.css
#  store:
#    - public/stylesheets/dialog.css
#    - public/stylesheets/new-dialog.css
#    - public/store/stylesheets/*.css
