common: &common
  :username: zangzing
  :api_key: R_c4a59a634afe6b4e7320b1b30069daa0

development:
  <<: *common

perftest:
  <<: *common

test:
  <<: *common

photos_production:
  <<: *common

photos_staging:
  <<: *common


eytest:
  <<: *common
