--- 
development:
  :login: zzadmin
  :password: sharezzphotos

perftest:
  :login: zzadmin
  :password: sharezzphotos

test:
  :login: zzadmin
  :password: sharezzphotos

photos_production:
  :login: alpha
  :password: zzrocks!

photos_staging:
  :login: zzadmin
  :password: sharezzphotos


eytest:
  :login: zzadmin
  :password: sharezzphotos

