#
#   Copyright 2010, ZangZing LLC;  All rights reserved.  http://www.zangzing.com
#
# Top level entries in each environment are for Paperclip.options
#  -image_options are for the Photo.image attachment
#  -local_image_options are for the Photo.local_image attachment
#
#  WARNING: INDENTATION HAS SEMANTIC MEANING! BE CAREFUL WHEN EDITING
#


#FOR All ENVS
common: &common
  local_image_options:
    url:         "/system/:attachment/:id/:id_:style.:extension"
    default_url: "/images/working.png"
  image_options:
    storage:        :s3
    path:           ":attachment/:id/:id_:style.:extension"
    url:            :s3_domain_url
    s3_credentials: <%=File.join(Rails.root, 'config', 's3.yml')%>   #Config file also contains :bucket
    default_url:    "/images/working.png"
    styles:
      medium: "1024x768>"
      thumb:  "120x120>"
    s3_headers:
      x-amz-storage-class: REDUCED_REDUNDANCY
      Expires:  <%=1.year.from_now.httpdate%>
    s3buckets:
      - alpha.dev.zangzing
      - bravo.dev.zangzing
      - charlie.dev.zangzing
      - delta.dev.zangzing
      - eco.dev.zangzing

development:
  <<: *common
  command_path: <%=ENV['IMAGEMAGICK_PATH']%> #look for imagemagick here
  log_command:  true
#  image_options:
#    storage: :Filesysem
#    path:    "/system/:attachment/:id/:id_:style.:extension"


test:
  <<: *common
  command_path: <%=ENV['IMAGEMAGICK_PATH']%> #look for imagemagick here

eydevelopment:
  <<: *common

eytest:
  <<: *common



production:
  <<: *common
  log:   false
  whiny: false
                      