#
#   Copyright 2010, ZangZing LLC;  All rights reserved.  http://www.zangzing.com
#
# Top level entries in each environment are for Paperclip.options
#  -image_options are for the Photo.image attachment
#  -local_image_options are for the Photo.local_image attachment
#
#  WARNING: INDENTATION HAS SEMANTIC MEANING! BE CAREFUL WHEN EDITING
#

# FOR ALL REMOTE Paperclip IMAGES (Can override per attachment below)
images_common: &images_common
  storage:        :s3
  path:           ":attachment/:id/:id_:style.:extension"
  url:            :s3_domain_url
  s3_credentials: <%=File.join(Rails.root, 'config', 's3.yml')%>
  s3_headers:
    x-amz-storage-class: REDUCED_REDUNDANCY
    Expires:  <%=1.year.from_now.httpdate%>
  s3buckets:
    - alpha.dev.zangzing
    - bravo.dev.zangzing
    - charlie.dev.zangzing
    - delta.dev.zangzing
    - eco.dev.zangzing

#FOR All ENVS
common: &common
  local_image_options:
    url:         "/system/:attachment/:id/:id_:style.:extension"
    default_url: "/images/working.png"
  picon_options:
    <<: *images_common
    default_url: "/images/album_no_pics.png"  
  image_options:
    <<: *images_common
    default_url: "/images/working.png"
    styles:
      medium: "1024x768>"
      thumb:  "120x120>"

development:
  <<: *common
  command_path: <%=ENV['IMAGEMAGICK_PATH']%> #look for imagemagick here
  log_command:  true

test:
  <<: *common
  command_path: <%=ENV['IMAGEMAGICK_PATH']%> #look for imagemagick here

eydevelopment:
  <<: *common

eytest:
  <<: *common

production:
  <<: *common
  log:   false
  whiny: false
                      