#
#   Copyright 2010, ZangZing LLC;  All rights reserved.  http://www.zangzing.com
#
# Top level entries in each environment are for Paperclip.options
#  -image_options are for the Photo.image attachment
#  -local_image_options are for the Photo.local_image attachment
#
#  WARNING: INDENTATION HAS SEMANTIC MEANING! BE CAREFUL WHEN EDITING
#

# FOR ALL REMOTE Paperclip IMAGES (Can override per attachment below)
images_common: &images_common
  storage:        :s3
  url:            :s3_domain_url
  s3_credentials: <%=File.join(Rails.root, 'config', 's3.yml')%>
  s3_headers:
    x-amz-storage-class: REDUCED_REDUNDANCY
    Expires:  <%=1.year.from_now.httpdate%>
  s3buckets:
    - alpha.dev.zangzing
    - bravo.dev.zangzing
    - charlie.dev.zangzing
    - delta.dev.zangzing
    - eco.dev.zangzing
    - foxtrot.dev.zangzing

#FOR All ENVS
common: &common
  local_image_options:
    path:        ":rails_root/public/system/:attachment/:id/:style/:id.:extension"
    url:         "/system/:attachment/:id/:style/:id.:extension"
    default_url: "/images/working.png"
  picon_options:
    <<: *images_common
    path:        ":attachment/:id/:filename"
    default_url: "/images/folders/blank.png"  
  image_options:
    <<: *images_common
    path:        ":directory/:style/:filename"
    default_url: "/images/working.png"
    styles:
      medium: "1024x768>"
      thumb: "120x120>"
    convert_options:
      thumb: '-strip -depth 8 -density 72 -quality 80'

development:
  <<: *common
  command_path: <%=ENV['IMAGEMAGICK_PATH']%> #look for imagemagick here
  log_command:  true

test:
  <<: *common
  command_path: <%=ENV['IMAGEMAGICK_PATH']%> #look for imagemagick here

eydevelopment:
  <<: *common

eysandbox:
  <<: *common


eytest:
  <<: *common

production:
  <<: *common
  log:   false
  whiny: false
                      