---
test:
  :consumer_key: 149830627
  :consumer_secret: bbcf09d3d2f6731afab642ec9de6a6ca


development:
  :consumer_key: 149830627
  :consumer_secret: bbcf09d3d2f6731afab642ec9de6a6ca

perftest:
  :consumer_key: 149830627
  :consumer_secret: bbcf09d3d2f6731afab642ec9de6a6ca

photos_production:
  :consumer_key: 149830626
  :consumer_secret: 9fd3eef0b1c3410d4dcbe8a82c1c3ed6

photos_staging:
  :consumer_key: 149830650
  :consumer_secret: 8bba1ccf698fb9bcc9e674551a16ad93
