# This points resque to the appropriate redis host and port

development:   localhost:6379
perftest:   localhost:6379
photos_production: localhost:6379
photos_staging:     localhost:6379
eytest:        localhost:6379
test:          localhost:6379     
