#
# s3.yml
#
# Credentials for s3 account
#


common: &common
  access_key_id: AKIAJZR7WODGPXONMRVA
  secret_access_key: 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

development:
  <<: *common

test:
  <<: *common

eydevelopment:
  <<: *common

eytest:
  <<: *common



production:
  <<: *common
