#
# s3.yml
#
# Credentials for aws are now stored in /var/chef/amazon.json
#


common: &common
  buckets: [d.1.zz, d.2.zz]
  reduced_redundancy: false

development:
  <<: *common

perftest:
  <<: *common

test:
  <<: *common

photos_production:
  <<: *common
  buckets: [1.zz, 2.zz, 3.zz, 4.zz]
  reduced_redundancy: false

photos_staging:
  <<: *common


eytest:
  <<: *common

