#
# s3.yml
#
# Credentials for s3 account
#


common: &common
  access_key_id: AKIAJZR7WODGPXONMRVA
  secret_access_key: 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
  buckets: [d.1.zz, d.2.zz]

development:
  <<: *common

perftest:
  <<: *common

test:
  <<: *common

eydevelopment:
  <<: *common
  buckets: [1.zz, 2.zz, 3.zz, 4.zz]

eysandbox:
  <<: *common


eytest:
  <<: *common



production:
  <<: *common
