#set up in api_consumer_timeout_patches.rb

:google: 3
#:picasa: 3 #google used
:flickr: 3
:yahoo: 3
:facebook: 3
:twitter: 3
:smugmug: 3
:photobucket: 3
:shutterfly: 3
:kodak: 3
:mslive: 3
