#set up in api_consumer_timeout_patches.rb

:google: 5
#:picasa: 3 #google used
:flickr: 5
:yahoo: 5
:facebook: 5
:twitter: 5
:smugmug: 5
:photobucket: 5
:shutterfly: 5
:kodak: 5
:mslive: 5
:mslive: 5
