#Google's one is used also for picasa
:google: <%= 5.seconds %>
:flickr: <%= 5.seconds %>
:yahoo: <%= 5.seconds %>
:facebook: <%= 5.seconds %>
:twitter: <%= 5.seconds %>
:smugmug: <%= 5.seconds %>
:photobucket: <%= 5.seconds %>
:shutterfly: <%= 5.seconds %>
:kodak: <%= 5.seconds %>
:mslive: <%= 5.seconds %>
:instagram: <%= 5.seconds %>