#Google's one is used also for picasa
:google: <%= 15.seconds %>
:flickr: <%= 15.seconds %>
:yahoo: <%= 15.seconds %>
:facebook: <%= 15.seconds %>
:twitter: <%= 15.seconds %>
:smugmug: <%= 15.seconds %>
:photobucket: <%= 15.seconds %>
:shutterfly: <%= 15.seconds %>
:kodak: <%= 15.seconds %>
:mslive: <%= 15.seconds %>
:instagram: <%= 15.seconds %>