---
development:
  :shared_secret: fd095cf29564dc9711169fd657cfd51f
  :api_key: l2bd6h6GW1FcoJDGy6h31pxKMsAWjSjH

test:
  :shared_secret: fd095cf29564dc9711169fd657cfd51f
  :api_key: l2bd6h6GW1FcoJDGy6h31pxKMsAWjSjH


eydevelopment:
  :shared_secret: 19a4c10a346ef517cc880411e2fbc8b4
  :api_key: bzyJIL3paLs5MbNDrOJNmQjikMOwa5sN

eytest:
  :shared_secret: 19a4c10a346ef517cc880411e2fbc8b4
  :api_key: bzyJIL3paLs5MbNDrOJNmQjikMOwa5sN


production:
  :shared_secret:
  :api_key:
