---
development:
  :consumer_secret: LVwYEbWO9XUMMuqVcIBlAEASOWLdoW7ufYujiYbzI
  :app_key: IzGoUFOmtnSFoebjtFWJCQ

perftest:
  :consumer_secret: LVwYEbWO9XUMMuqVcIBlAEASOWLdoW7ufYujiYbzI
  :app_key: IzGoUFOmtnSFoebjtFWJCQ

test:
  :consumer_secret: LVwYEbWO9XUMMuqVcIBlAEASOWLdoW7ufYujiYbzI
  :app_key: IzGoUFOmtnSFoebjtFWJCQ

eydevelopment:
  :consumer_secret: LVwYEbWO9XUMMuqVcIBlAEASOWLdoW7ufYujiYbzI
  :app_key: IzGoUFOmtnSFoebjtFWJCQ

eysandbox:
  :consumer_secret: LVwYEbWO9XUMMuqVcIBlAEASOWLdoW7ufYujiYbzI
  :app_key: IzGoUFOmtnSFoebjtFWJCQ


eytest:
  :consumer_secret: LVwYEbWO9XUMMuqVcIBlAEASOWLdoW7ufYujiYbzI
  :app_key: IzGoUFOmtnSFoebjtFWJCQ


production:
  :consumer_secret:
  :app_key: 
