---
development:
  :consumer_secret: kSAdo76olC43lX6EyC7xNQjBF1Geh0CZdO505uFjKMo
  :app_key: 8NTjD0j6csRr1aGrGGuLA

test:
  :consumer_secret: kSAdo76olC43lX6EyC7xNQjBF1Geh0CZdO505uFjKMo
  :app_key: 8NTjD0j6csRr1aGrGGuLA

development-engineyard:
  :consumer_secret: kSAdo76olC43lX6EyC7xNQjBF1Geh0CZdO505uFjKMo
  :app_key: 8NTjD0j6csRr1aGrGGuLA

test-engineyard:
  :consumer_secret: kSAdo76olC43lX6EyC7xNQjBF1Geh0CZdO505uFjKMo
  :app_key: 8NTjD0j6csRr1aGrGGuLA


production:
  :consumer_secret:
  :app_key: 
