---
development:
  :consumer_secret: LVwYEbWO9XUMMuqVcIBlAEASOWLdoW7ufYujiYbzI
  :app_key: IzGoUFOmtnSFoebjtFWJCQ

perftest:
  :consumer_secret: LVwYEbWO9XUMMuqVcIBlAEASOWLdoW7ufYujiYbzI
  :app_key: IzGoUFOmtnSFoebjtFWJCQ

test:
  :consumer_secret: LVwYEbWO9XUMMuqVcIBlAEASOWLdoW7ufYujiYbzI
  :app_key: IzGoUFOmtnSFoebjtFWJCQ

photos_production:
  :consumer_secret: LVwYEbWO9XUMMuqVcIBlAEASOWLdoW7ufYujiYbzI
  :app_key: IzGoUFOmtnSFoebjtFWJCQ

photos_staging:
  :consumer_secret: LVwYEbWO9XUMMuqVcIBlAEASOWLdoW7ufYujiYbzI
  :app_key: IzGoUFOmtnSFoebjtFWJCQ


eytest:
  :consumer_secret: LVwYEbWO9XUMMuqVcIBlAEASOWLdoW7ufYujiYbzI
  :app_key: IzGoUFOmtnSFoebjtFWJCQ

