---
development:
  :consumer_secret: 44f4e5a139ef78d9ca7f35fa641b5d54b7043223
  :app_key: dj0yJmk9YWx6d3gxZXJMbk15JmQ9WVdrOU5uRmhWVlJUTjJzbWNHbzlNQS0tJnM9Y29uc3VtZXJzZWNyZXQmeD1iNA--
  :app_id: 6qaUTS7k

perftest:
  :consumer_secret: 44f4e5a139ef78d9ca7f35fa641b5d54b7043223
  :app_key: dj0yJmk9YWx6d3gxZXJMbk15JmQ9WVdrOU5uRmhWVlJUTjJzbWNHbzlNQS0tJnM9Y29uc3VtZXJzZWNyZXQmeD1iNA--
  :app_id: 6qaUTS7k

test:
  :consumer_secret: 669115f39f45f7be301dcc5443ffae67bc7d6b1c
  :app_key: dj0yJmk9TVFrMnFCZnlSeDBNJmQ9WVdrOU1rOUdiRTFtTkhNbWNHbzlNQS0tJnM9Y29uc3VtZXJzZWNyZXQmeD1iMg--
  :app_id: 2OFlMf4s

photos_production:
  :consumer_secret: 1dfd9a76919afa5aae7488d271f7e62e1442e4c0
  :app_key: dj0yJmk9VXl0RWRFVGpyT1h6JmQ9WVdrOWJHVklia2xrTm5NbWNHbzlNQS0tJnM9Y29uc3VtZXJzZWNyZXQmeD0yNw--
  :app_id: leHnId6s

photos_staging:
  :consumer_secret: 9457892b4ce290db9435aee94ed6b61b0e2fa21e
  :app_key: dj0yJmk9b1IzNFNsaHkxNmROJmQ9WVdrOU5tc3dUMUIwTnpBbWNHbzlNQS0tJnM9Y29uc3VtZXJzZWNyZXQmeD04ZA
  :app_id: 6k0OPt70

