#
# This is the dumping ground for generic zz environment related stuff
# I got tired of creating new .yml files for every little switch so
# we can put the bulk of them here from now on.
#


common: &common
  reserved_names: false
  resque_zza_id: "dev.photos/svr"
  album_email_host: "greg-post.zangzing.com"
  async_job_timeout: 20
  async_connector_timeout: 30
  requires_http_auth: true
  agent_download_url_mac: "http://staging.downloads.zangzing.com/agent/darwin/ZangZing-Setup(STAGED).pkg"
  agent_download_url_win: "http://staging.downloads.zangzing.com/agent/win32/ZangZing-Setup(STAGED).exe"

development:
  <<: *common
  reserved_names: false
  resque_zza_id: "dev.photos/svr"
  async_connector_timeout: 7200
  async_job_timeout: 7200

perftest:
  <<: *common
  resque_zza_id: "perftest.photos/svr"
  async_connector_timeout: 7200
  async_job_timeout: 7200

test:
  <<: *common
  resque_zza_id: "dev.photos/svr"

photos_production:
  <<: *common
  reserved_names: true
  resque_zza_id: "photos/svr"
  album_email_host: "zangzing.com"
#  requires_http_auth: false
  agent_download_url_mac: "http://downloads.zangzing.com/agent/darwin/ZangZing-Setup.pkg"
  agent_download_url_win: "http://downloads.zangzing.com/agent/win32/ZangZing-Setup.exe"

photos_staging:
  <<: *common
  reserved_names: true
  resque_zza_id: "staging.photos/svr"
  album_email_host: "staging.zangzing.com"


eytest:
  <<: *common

