#!/bin/bash

# pull in the seed data to the test db
# we run this before executing the tests
# to get the database into a known state

/usr/local/mysql/bin/mysql -hlocalhost -uroot server_test < server_test.seed
/usr/local/mysql/bin/mysql -hlocalhost -uroot cache_test < cache_test.seed
