class AddOuterEmailTemplate < ActiveRecord::Migration
  def self.up
    add_column :email_templates, :html_body, :text
    add_column :email_templates, :text_body, :text

    outer = Email.outer_template.create!
    template = EmailTemplate.create!(:email_id => outer.id, :name => 'autogenerated_outer_template', :mc_campaign_id => 'n/a')
    outer.update_attribute(:production_template_id, template.id)
  end

  def self.down
    remove_column :email_templates, :text_body, :html_body
    Email.outer_template.destroy_all
  end
end
